services:

  ecommerce.api.orders:
    image: ${DOCKER_REGISTRY-}ecommerceapiorders
    build:
      context: ECommerce.Api.Orders
      dockerfile: Dockerfile


  ecommerce.api.products:
    image: ${DOCKER_REGISTRY-}ecommerceapiproducts
    build:
      context: ECommerce.Api.Products
      dockerfile: Dockerfile


  ecommerce.api.search:
    image: ${DOCKER_REGISTRY-}ecommerceapisearch
    build:
      context: ECommerce.Api.Search
      dockerfile: Dockerfile


  ecommerce.api.customers:
    image: ${DOCKER_REGISTRY-}ecommerceapicustomers
    build:
      context: ECommerce.Api.Customers
      dockerfile: Dockerfile

